from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from pydantic import BaseModel
from pptx import Presentation
from pptx.util import Inches, Pt
from services.ai_service import ai_service
import os
import uuid

router = APIRouter(prefix="/presentation", tags=["Presentation"])

class PresentationRequest(BaseModel):
    topic: str
    num_slides: int = 5
    language: str = "English"

def delete_file(path: str):
    if os.path.exists(path):
        os.remove(path)

@router.post("/generate")
async def generate_presentation(req: PresentationRequest, background_tasks: BackgroundTasks):
    if not ai_service.has_ai:
        raise HTTPException(status_code=400, detail="AI Service unavailable")
    
    try:
        # 1. Get Content from AI
        content = await ai_service.generate_presentation_content(req.topic, req.num_slides, req.language)
        
        # 2. Create PPT
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = content.get("title", req.topic)
        subtitle.text = f"Generated by QuizAI | {req.language}"
        
        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        
        for slide_data in content.get("slides", []):
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = slide_data.get("title", "Slide")
            
            tf = body_shape.text_frame
            for point in slide_data.get("content", []):
                p = tf.add_paragraph()
                p.text = point
                p.level = 0

        # 3. Save to temporary file
        filename = f"gen_ppt_{uuid.uuid4().hex}.pptx"
        file_path = os.path.join("static", "temp", filename)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        prs.save(file_path)
        
        # 4. Return File
        # Background task to clean up file after sending
        background_tasks.add_task(delete_file, file_path)
        
        return FileResponse(
            path=file_path,
            filename=f"{req.topic.replace(' ', '_')}.pptx",
            media_type='application/vnd.openxmlformats-officedocument.presentationml.presentation'
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
